### ISSUE TITLE
Tag 0.3

### ISSUE THREAD

**Issue by benlk** [INN/doubleclick-for-wp#83]
## Todo list:

- [x] https://github.com/INN/doubleclick-for-wp/issues/86
- [x] https://github.com/INN/doubleclick-for-wp/issues/69
- [x] inn_nerds -> innlabs
- [x] copy https://github.com/INN/super-cool-ad-inserter-plugin/blob/master/docs/developers-release-checklist.md into this plugin's docs folder with relevant instructions for testing
- [x] check with GAM to see if there's a way to run test ads
- [x] bump version number to 0.3: https://github.com/INN/doubleclick-for-wp/pull/89
- [x] tag and push
- [x] release notes on github
- [x] where is the screenshot in https://wordpress.org/plugins/doubleclick-for-wp/ coming from and how do we update it?
- [x] release.sh

**Comment by benlk** [comment]
https://github.com/INN/doubleclick-for-wp/releases/tag/v0.3

**Comment by benlk** [comment]
Via https://github.com/INN/docs/blob/master/projects/wordpress-plugins/release.sh.md#updating-the-assets-directory-of-svn, removed the image from the assets directory.
